project:
  type: book
  output-dir: docs

book:
  title: &book_title "The Little Book of Artificial Intelligence"
  subtitle: &book_subtitle "Version 0.1.6"
  author: &book_author "Duc-Tam Nguyen"
  date: &book_date "2025-09-21"
  output-file: book
  chapters:
    - index.qmd
    - books/en-US/volume_1.qmd
    - books/en-US/volume_2.qmd
    - books/en-US/volume_3.qmd
    - books/en-US/volume_4.qmd
    - books/en-US/volume_5.qmd
    - books/en-US/volume_6.qmd
    - books/en-US/volume_7.qmd

website:
  title: *book_title
  page-navigation: true
  navbar:
    search: true
    right:
      - text: *book_subtitle 
      - icon: github
        href: https://github.com/little-book-of/ai
        aria-label: GitHub

format:
  html:
    sidebar: true
    toc: true
    toc-location: left
    toc-depth: 3
    number-sections: false
    theme: [cosmo, brand]
  epub:
    title: *book_title
    subtitle: *book_subtitle
    author: *book_author
    date: *book_date
    toc: true 
    toc-depth: 3
    number-sections: false
  pdf:
    title: *book_title
    subtitle: *book_subtitle
    author: *book_author
    date: *book_date
    toc: true 
    toc-depth: 3
    number-sections: false
    colorlinks: true
  latex:
    number-sections: false
